repos:
  - repo: local
    hooks:
      - id: test
        name: Run tests
        entry: uv run task test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]