python_tests(
    name="tests",
    dependencies=[
        "apps/app_1/src:src",
        "//:default#pytest-asyncio",
        "//:default#httpx",
    ],
)

python_test_utils(
    name="test_utils",
)
